# Generated by Django 3.2.3 on 2021-06-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_entry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_tracked',
            field=models.BooleanField(default=False),
        ),
    ]
